/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ShipCreateNestedManyWithoutPlayersInput } from "./ShipCreateNestedManyWithoutPlayersInput";
import { Type } from "class-transformer";
import { SquadronCreateNestedManyWithoutPlayersInput } from "./SquadronCreateNestedManyWithoutPlayersInput";

@InputType()
class PlayerCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  level?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  experience?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currency?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  items?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ShipCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => ShipCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => ShipCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  ships?: ShipCreateNestedManyWithoutPlayersInput;

  @ApiProperty({
    required: false,
    type: () => SquadronCreateNestedManyWithoutPlayersInput,
  })
  @ValidateNested()
  @Type(() => SquadronCreateNestedManyWithoutPlayersInput)
  @IsOptional()
  @Field(() => SquadronCreateNestedManyWithoutPlayersInput, {
    nullable: true,
  })
  squadrons?: SquadronCreateNestedManyWithoutPlayersInput;
}

export { PlayerCreateInput as PlayerCreateInput };
