/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PlayerService } from "../player.service";
import { PlayerCreateInput } from "./PlayerCreateInput";
import { Player } from "./Player";
import { PlayerFindManyArgs } from "./PlayerFindManyArgs";
import { PlayerWhereUniqueInput } from "./PlayerWhereUniqueInput";
import { PlayerUpdateInput } from "./PlayerUpdateInput";
import { ShipFindManyArgs } from "../../ship/base/ShipFindManyArgs";
import { Ship } from "../../ship/base/Ship";
import { ShipWhereUniqueInput } from "../../ship/base/ShipWhereUniqueInput";
import { SquadronFindManyArgs } from "../../squadron/base/SquadronFindManyArgs";
import { Squadron } from "../../squadron/base/Squadron";
import { SquadronWhereUniqueInput } from "../../squadron/base/SquadronWhereUniqueInput";

export class PlayerControllerBase {
  constructor(protected readonly service: PlayerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Player })
  async createPlayer(@common.Body() data: PlayerCreateInput): Promise<Player> {
    return await this.service.createPlayer({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        level: true,
        name: true,
        experience: true,
        currency: true,
        items: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Player] })
  @ApiNestedQuery(PlayerFindManyArgs)
  async players(@common.Req() request: Request): Promise<Player[]> {
    const args = plainToClass(PlayerFindManyArgs, request.query);
    return this.service.players({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        level: true,
        name: true,
        experience: true,
        currency: true,
        items: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async player(
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Player | null> {
    const result = await this.service.player({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        level: true,
        name: true,
        experience: true,
        currency: true,
        items: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePlayer(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() data: PlayerUpdateInput
  ): Promise<Player | null> {
    try {
      return await this.service.updatePlayer({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          level: true,
          name: true,
          experience: true,
          currency: true,
          items: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Player })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePlayer(
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Player | null> {
    try {
      return await this.service.deletePlayer({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          level: true,
          name: true,
          experience: true,
          currency: true,
          items: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/ships")
  @ApiNestedQuery(ShipFindManyArgs)
  async findShips(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Ship[]> {
    const query = plainToClass(ShipFindManyArgs, request.query);
    const results = await this.service.findShips(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        speed: true,
        cargoCapacity: true,
        power: true,
        name: true,

        player: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ships")
  async connectShips(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: ShipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ships: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ships")
  async updateShips(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: ShipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ships: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ships")
  async disconnectShips(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: ShipWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ships: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/squadrons")
  @ApiNestedQuery(SquadronFindManyArgs)
  async findSquadrons(
    @common.Req() request: Request,
    @common.Param() params: PlayerWhereUniqueInput
  ): Promise<Squadron[]> {
    const query = plainToClass(SquadronFindManyArgs, request.query);
    const results = await this.service.findSquadrons(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        members: true,

        player: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/squadrons")
  async connectSquadrons(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: SquadronWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      squadrons: {
        connect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/squadrons")
  async updateSquadrons(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: SquadronWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      squadrons: {
        set: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/squadrons")
  async disconnectSquadrons(
    @common.Param() params: PlayerWhereUniqueInput,
    @common.Body() body: SquadronWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      squadrons: {
        disconnect: body,
      },
    };
    await this.service.updatePlayer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
